config/routes.rb
SportsInventory::Application.routes.draw do

  resources :items do
    collection do
      get :sell
      get :search
    end

   

  end

  root :to => 'items#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_and_belongs_to_many :items
  has_many :prices
  attr_accessible :brand_name
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :brands
  has_many :prices
  attr_accessible  :category, :item_name
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :brand
  belongs_to :item
  attr_accessible :cost, :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	
	def new
		@item = Item.new
	end

	def index
		@items = Item.all
	end

	def create
		
		items = params.slice('item_name', 'category')
		@item = Item.find_or_create_by_item_name(params[:item_name])
		@item.save
		@brand = Brand.find_or_create_by_brand_name(params[:brand_name])
		@item.brands << @brand unless @item.brands.include?(@brand)
		price_params = params.slice('cost', 'quantity')
		@price = @item.prices.where(brand_id: @brand.id).first
		if @price
			@price.quantity += params[:quantity].to_i
		else
			@price = Price.new(price_params)
			@price.brand = @brand
			@price.item = @item
		end
		@price.save

		redirect_to items_path
	end

	def search
		# binding.pry
	end

	def sell

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="container">
  <h1 align="center">  Sports Center</h1>
  <div class="box-body">
    <div class="table-responsive ">
      <table border="1" class="table table-bordered table-hover"> 
        <thead> 
          <th> 
            Name of Item
          </th>
          <th> 
            Brand
          </th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Actions</th>
          
        </thead>
          
        <tbody> 
          <% @items.each do |item| %>
            <% item.brands.each do |brand| %>
              <tr>
                <td><%= item.item_name %></td>
                <td><%= brand.brand_name %></td>
                <% price = item.prices.where(brand_id: brand.id).first %>
                <td><%= price ? price.cost : '-' %></td>
                <td><%= price ? price.quantity : '-' %></td>
                <td><%= 'NA' %></td>
              </tr>
            <% end %>
          <% end %>
          
        </tbody>
        
      </table>
    </div>
  </div>
<%= link_to 'Add new item', new_item_path, class: 'btn btn-success' %>
</div>

app/views/items/new.html.erb
<div class="container col col-md-12">
  <h2>Add New Sports Items</h2>
  
    <%= form_tag('/items', method: "post", class: 'form-horizontal') do %>
      <div class="form-group">
        <%= label_tag(:item_name, "Name of Item:", class: "col-sm-2 control-label") %>
        <div class="col-sm-10">
          <%= text_field_tag(:item_name, params[:item_name], class: 'form-control')  %>
        </div>
      </div>
      <%= label_tag(:category, "Category")%>
      <%= radio_button_tag :category, "indoor"%>Indoor
      <%= radio_button_tag :category, "outdoor"%>Outdoor<br>
      <%= label_tag(:brand_name, "Name of Brand:") %>
      <%= text_field_tag(:brand_name) %><br>
      <%= label_tag(:cost, "Price of the item")%>
      <%= text_field_tag(:cost)%><br>
      <%= label_tag(:quantity, "Quantity")%>
      <%= text_field_tag(:quantity)%><br>
      <%= submit_tag("Add") %>
    <% end %>
  
</div>

app/views/items/search.html.erb
I am dipendra shrestha.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsInventory</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>